params:
  split_size: 0.2
  ts_split: 5
  random_state: 2023
  holiday_id: DE-SH
  target_col: net_sales

raw_data:
  path: data/raw.parquet

weather_data:
  path: data/weather_data.parquet

processed:
  dir: data/processed
  X_train:
    name: X_train.parquet
    path: ${processed.dir}/${processed.X_train.name}
  X_test:
    name: X_test.parquet
    path: ${processed.dir}/${processed.X_test.name}
  y_train:
    name: y_train.parquet
    path: ${processed.dir}/${processed.y_train.name}
  y_test:
    name: y_test.parquet
    path: ${processed.dir}/${processed.y_test.name}


mlflow_tracking_uri: https://dagshub.com/ericyaang/restaurant-sales-forecasting.mlflow
